# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['run_async']

# %% ../nbs/00_core.ipynb #cc1ba640
import asyncio, concurrent.futures

def run_async(coro):
    "Run an async coroutine safely from sync code, even inside a running event loop (e.g. ipymini)"
    with concurrent.futures.ThreadPoolExecutor(max_workers=1) as pool:
        fut = pool.submit(asyncio.run, coro)
        return fut.result()
